pipeline {
   agent {
        node {
            label 'master'
        }
    }
   stages {
      stage('Preparation') {
         steps {
            cleanWs()
            git credentialsId: 'git_access', branch: 'main', url: "https://github.com/olivern300/cicd-java-demo.git"
         }
      }
      stage('Create Application Build') {
         steps {
            sh '''cd hello-world
               mvn install clean package'''
         }
      }
      stage('Deploy Build') {
         steps {
            sh '''cd ansible
               ansible-playbook -i Inventory deploy-on-tomcat.yaml'''
         }
      }
   }
}
