---
- name: "Create Docker image and Push to repository"
  hosts: jenkins
  become: yes
  tasks:
    - name: Log into DockerHub
      community.general.docker_login:
        username: "{{ dockerusr }}"
        password: "{{ dockerpass }}"
    - name: Build image
      community.docker.docker_image:
        build:
          path: /var/lib/jenkins/workspace/deploy-on-docker/hello-world/.
        name: olivern300/hello-world
        tag: latest
        push: true
        source: build
    - name: Remove latest image
      docker_image:
        state: absent
        name: olivern300/hello-world
        tag: latest
    - name: Log out of DockerHub
      docker_login:
        state: absent
